---
- hosts: all
  become: yes
  tasks:
    - name: Install fish through system package manager
      ansible.builtin.package:
        name: fish
        state: present
    
    - name: Setup Cargo
      ansible.builtin.import_role:
        - robertdebock.cargo
    
    