---
- hosts: all
  become: yes
  roles:
    - robertdebock.cargo
    - robertdebock.bootstrap
    - robertdebock.buildtools
  tasks:
    - name: Set up build deps
      ansible.builtin.package:
        name: 
          - build-essential
          - cmake
          - meson
        state: present
        
    - name: Install exa and starship through Cargo
      community.general.cargo:
        name:
          - exa
          - starship
        state: present

    - name: Setup aliases for ls
      ansible.builtin.shell: |
        echo 'eval "$(starship init bash)"' >> ~/.bashrc
        echo 'alias ls="exa --icons -lhi --git"' >> ~/.bashrc
    - name: Say done
      ansible.builtin.debug:
        msg: Done
