---
- hosts: all
  become: yes
  roles:
    - robertdebock.cargo
    - robertdebock.bootstrap
    - robertdebock.buildtools
  tasks:

    - name: Install exa and starship through Cargo
      community.general.cargo:
        name: "{{ item }}"
        with_items:
          - exa
          - starship

    - name: Setup aliases for ls
      ansible.builtin.shell: |
        echo 'eval "$(starship init bash)"' >> ~/.bashrc
        echo 'alias ls="exa --icons -lhi --git"' >> ~/.bashrc
    - name: Say done
      ansible.builtin.debug:
        msg: Done
