---
- hosts: swarm-01
  become: yes
  vars_files: 
  - credentials.yml
  - vars.yml
  tasks:
  - name: Copy templated Docker compose file to the system
    ansible.builtin.template:
      src: docker-compose.yml.j2
      dest: docker-compose.yml
  - name: initialize swarm cluster
      shell: >
        docker swarm init
        --advertise-addr={{ swarm_iface | default('eth0') }}:2377
      when: "'swarm_manager_operational' not in groups"
      register: bootstrap_first_node

    - name: add initialized host to swarm_manager_operational group
      add_host:
        hostname: "{{ play_hosts[0] }}"
        groups: swarm_manager_operational
      when: bootstrap_first_node | changed
  - name: Install prerequsites for Docker stack
    ansible.builtin.apt:
      name:
        - python3-jsondiff
      state: present
  - name: Start Docker stack
    community.docker.docker_stack:
      state: present
      name: "{{ stack_name }}"
      compose:
        - docker-compose.yml