---
- hosts: all
  become: yes
  roles:
    - ohing504.swarmpit
    - inhumantsar.traefik-swarm
  vars_files: 
  - credentials.yml
  - vars.yml
  tasks:
  - name: Copy templated Docker compose file to the system.
    ansible.builtin.rsync:

  - name: Install prerequsites for Docker stack
    ansible.builtin.apt:
      name:
        - python3-jsondiff
      state: present

  - name: Start Docker stack
    community.docker.docker_stack:
      state: present
      name: "{{ stack_name }}"
      compose:
        - docker-compose.yml