---
- hosts: swarm-01
  become: yes
  vars_files: 
  - credentials.yml
  - vars.yml
  tasks:
  - name: Copy templated Docker compose file to the system
    ansible.builtin.template:
      src: docker-compose.yml.j2
      dest: docker-compose.yml
  - name: Start docker stack
    ansible.builtin.shell: |
      docker stack deploy --compose-file docker-compose.yml {{ stack_name }}