---
- hosts: all
  become: yes
  roles:
    - ohing504.swarmpit
    - inhumantsar.traefik-swarm
  vars_files: 
  - credentials.yml
  - vars.yml
  tasks:
  - name: Copy templated Docker compose file to the system.
    ansible.builtin.template:
      src: docker-compose.yml.j2
      dest: docker-compose.yml
      mode: "0644"

  - name: Install prerequsites for Docker stack
    ansible.builtin.apt:
      name:
        - python3-jsondiff
      state: present
  - name: Remove stack
    community.docker.docker_stack:
      name: portainer
      state: absent

  - name: Start Docker stack
    community.docker.docker_stack:
      state: present
      name: "{{ stack_name }}"
      compose:
        - docker-compose.yml