---
- hosts: all
  become: yes
  roles:
    - ohing504.swarmpit
    - inhumantsar.traefik-swarm
  vars_files: 
  - credentials.yml
  - vars.yml
  tasks:
  - name: Install prerequsites for Docker stack
    ansible.builtin.apt:
      name:
        - python3-jsondiff
      state: present
  - name: Copy templated stack to host
    ansible.builtin.template:
      src: svc/stack.yml.j2
      dest: docker-compose.yml
      mode: 0644
      state: touch
      
  - name: Start Docker stack
    community.docker.docker_stack:
      state: present
      name: "{{ stack_name }}"
      compose:
        - docker-compose.yml
