roles:
    - robertdebock.cargo
    - robertdebock.bootstrap
    - robertdebock.buildtools
    - robertdebock.update
    - geerlingguy.security
    - geerlingguy.pip
    - artis3n.tailscale
    - geerlingguy.docker
    - oefenweb.keepalived
    - alecunsolo.cockpit
    - mrlesmithjr.manage_lvm
collections:
  - community.general
