roles:
    - robertdebock.cargo
    - robertdebock.bootstrap
    - robertdebock.buildtools
    - robertdebock.update
    - geerlingguy.security
    - geerlingguy.pip
    - artis3n.tailscale
    - geerlingguy.docker
    - alecunsolo.cockpit

collections:
  - community.general
