---
- hosts: all
  become: true
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - mrlesmithjr.manage-lvm
    - mrlesmithjr.ansible-debian-autoupdates
  vars_files:
    - credentials.yml
    - vars.yml
  tasks:
  - name: Run another playbook
    ansible.builtin.import_playbook: deploy.yml