---
- hosts: all
  become: true
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - geerlingguy.kubernetes
    - mrlesmithjr.manage-lvm
    - mrlesmithjr.ansible-debian-autoupdates
  vars_files:
    - credentials.yml
    - vars.yml