---
- hosts: all
  become: true
  roles:
    - robertdebock.update
    - geerlingguy.pip
    - geerlingguy.docker
    - thomasjpfan.docker-swarm
    - mrlesmithjr.manage-lvm
    - mrlesmithjr.ansible-debian-autoupdates
  vars_files:
    - credentials.yml
    - vars.yml