---
- hosts: all
  become: yes
  
  vars_files:
    - credentials.yml
  
  tasks:
  - name: Setup Docker
    ansible.builtin.import_role:
      - geerlingguy.pip
      - geerlingguy.docker
  - name: Create docker swarm
    ansible.builtin.import_playbook:
        - roles/aur/dswarm/deploy-swarm.yml