---
- hosts: all
  become: true
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
  vars_files:
    - credentials.yml
    - vars.yml
  tasks:
  - name: Setup Swarm
    ansible.builtin.include_tasks: roles/dswarm/deploy-swarm.yml