---
- hosts: all
  become: true

  roles:
    - robertdebock.update
    - geerlingguy.security
    - geerlingguy.pip
    - artis3n.tailscale
    - geerlingguy.docker
    - alecunsolo.cockpit
  vars_files:
    - credentials.yml
    - vars.yml
  tasks:
    - name: matra Copy templated stack to host
    - hosts: matra
      ansible.builtin.copy:
        src: svc/fileserver.yml
        dest: docker-compose.yml

    - name: all > Start Docker compose file
      ansible.builtin.shell: |
        docker compose up -d
