apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: deluge
  name: deluge
spec:
  ports:
    - name: "6881"
      port: 6881
      targetPort: 6881
    - name: 6881-udp
      port: 6881
      protocol: UDP
      targetPort: 6881
    - name: "8112"
      port: 8112
      targetPort: 8112
    - name: "51413"
      port: 51413
      targetPort: 51413
    - name: 51413-udp
      port: 51413
      protocol: UDP
      targetPort: 51413
    - name: "58846"
      port: 58846
      targetPort: 58846
    - name: "58946"
      port: 58946
      targetPort: 58946
  selector:
    io.kompose.service: deluge
status:
  loadBalancer: {}
