apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: gitea
  name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: gitea
    spec:
      containers:
        - env:
            - name: USER_GID
              value: "1000"
            - name: USER_UID
              value: "1000"
          image: gitea/gitea
          name: gitea
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /etc/localtime
              name: gitea-claim0
              readOnly: true
            - mountPath: /etc/timezone
              name: gitea-claim1
              readOnly: true
            - mountPath: /data
              name: gitea-claim2
            - mountPath: /storage
              name: gitea-claim3
      hostname: TypekMatus
      restartPolicy: Always
      volumes:
        - name: gitea-claim0
          persistentVolumeClaim:
            claimName: gitea-claim0
            readOnly: true
        - name: gitea-claim1
          persistentVolumeClaim:
            claimName: gitea-claim1
            readOnly: true
        - name: gitea-claim2
          persistentVolumeClaim:
            claimName: gitea-claim2
        - name: gitea-claim3
          persistentVolumeClaim:
            claimName: gitea-claim3
status: {}
