apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jellyfin
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: jellyfin
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          image: lscr.io/linuxserver/jellyfin
          name: jellyfin
          ports:
            - containerPort: 8096
            - containerPort: 8920
          resources: {}
          volumeMounts:
            - mountPath: /etc/localtime
              name: jellyfin-claim0
              readOnly: true
            - mountPath: /config
              name: jellyfin-claim1
            - mountPath: /storage
              name: jellyfin-claim2
            - mountPath: /transcode
              name: jellyfin-claim3
      hostname: TypekMatus
      restartPolicy: Always
      volumes:
        - name: jellyfin-claim0
          persistentVolumeClaim:
            claimName: jellyfin-claim0
            readOnly: true
        - name: jellyfin-claim1
          persistentVolumeClaim:
            claimName: jellyfin-claim1
        - name: jellyfin-claim2
          persistentVolumeClaim:
            claimName: jellyfin-claim2
        - name: jellyfin-claim3
          persistentVolumeClaim:
            claimName: jellyfin-claim3
status: {}
