apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nextcloud
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: nextcloud
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          image: lscr.io/linuxserver/nextcloud
          name: nextcloud
          ports:
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /etc/localtime
              name: nextcloud-claim0
              readOnly: true
            - mountPath: /config
              name: nextcloud-claim1
            - mountPath: /storage
              name: nextcloud-claim2
            - mountPath: /data
              name: nextcloud-claim3
      hostname: TypekMatus
      restartPolicy: Always
      volumes:
        - name: nextcloud-claim0
          persistentVolumeClaim:
            claimName: nextcloud-claim0
            readOnly: true
        - name: nextcloud-claim1
          persistentVolumeClaim:
            claimName: nextcloud-claim1
        - name: nextcloud-claim2
          persistentVolumeClaim:
            claimName: nextcloud-claim2
        - name: nextcloud-claim3
          persistentVolumeClaim:
            claimName: nextcloud-claim3
status: {}
