apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: syncthing
  name: syncthing
spec:
  ports:
    - name: "8384"
      port: 8384
      targetPort: 8384
    - name: "21027"
      port: 21027
      protocol: UDP
      targetPort: 21027
    - name: "22000"
      port: 22000
      targetPort: 22000
  selector:
    io.kompose.service: syncthing
status:
  loadBalancer: {}
