apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: traefik
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: traefik
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          image: traefik
          name: traefik
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /etc/traefik
              name: traefik-claim0
            - mountPath: /storage
              name: traefik-claim1
            - mountPath: /etc/localtime
              name: traefik-claim2
              readOnly: true
            - mountPath: /var/run/docker.sock
              name: traefik-claim3
              readOnly: true
      hostname: TypekMatus
      restartPolicy: Always
      volumes:
        - name: traefik-claim0
          persistentVolumeClaim:
            claimName: traefik-claim0
        - name: traefik-claim1
          persistentVolumeClaim:
            claimName: traefik-claim1
        - name: traefik-claim2
          persistentVolumeClaim:
            claimName: traefik-claim2
            readOnly: true
        - name: traefik-claim3
          persistentVolumeClaim:
            claimName: traefik-claim3
            readOnly: true
status: {}
