apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: uptimekuma
  name: uptimekuma
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: uptimekuma
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: uptimekuma
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          image: louislam/uptime-kuma
          name: uptimekuma
          ports:
            - containerPort: 3001
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: uptimekuma-claim0
            - mountPath: /storage
              name: uptimekuma-claim1
            - mountPath: /etc/localtime
              name: uptimekuma-claim2
              readOnly: true
      hostname: TypekMatus
      restartPolicy: Always
      volumes:
        - name: uptimekuma-claim0
          persistentVolumeClaim:
            claimName: uptimekuma-claim0
        - name: uptimekuma-claim1
          persistentVolumeClaim:
            claimName: uptimekuma-claim1
        - name: uptimekuma-claim2
          persistentVolumeClaim:
            claimName: uptimekuma-claim2
            readOnly: true
status: {}
