---
- hosts: fatra
  become: true
  tasks:
    - name: Copy templated stack to host 
      hosts: fatra
      ansible.builtin.copy:
        src: ../svc/missioncritical.yml
        dest: docker-compose.yml

    - name: Start Docker compose file
      ansible.builtin.shell: |
        docker compose up -d
