version: "3.9"
name: server
services:

  gitea:
    container_name: gitea
    environment:
      TZ: Europe/Bratislava
      USER_GID: 1000
      USER_UID: 1000
    hostname: Gitea
    image: gitea/gitea
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3000
      published: 3000
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /etc/timezone
      target: /etc/timezone
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /mnt/gitea/data
      target: /data
      bind:
        create_host_path: true
    - type: bind
      source: /mnt/storage
      target: /storage
      bind:
        create_host_path: true

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CLI_ARGS= #optional
    volumes:
      - /mnt/duplicati/config:/config
      - /mnt/duplicati/backups:/backups
      - /mnt:/source
    ports:
      - 8200:8200
    restart: unless-stopped
  nextcloud:
      image: lscr.io/linuxserver/nextcloud:latest
      container_name: nextcloud
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Bratislava
      volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/config/nextcloud:/config
      - /mnt/storage/nextcloud:/storage
      - /mnt/data/nextcloud:/data
      ports:
        - 443:443
      restart: unless-stopped
  yacht:
    image: selfhostedpro/yacht:devel
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8000:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./config:/config
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
