version: "3.9"

services:
  jellyfin:
    container_name: jellyfin
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/Bratislava
    hostname: DockSTARTer
    image: lscr.io/linuxserver/jellyfin
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 200k
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8096
      published: 8096
      protocol: tcp
    - mode: ingress
      target: 8920
      published: 8920
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /mnt/config/appdata/jellyfin
      target: /config
      bind:
        create_host_path: true
    - type: bind
      source: /mnt/storage
      target: /storage
      bind:
        create_host_path: true
    - type: bind
      source: /tmp
      target: /transcode
      bind:
        create_host_path: true

  duplicati:
      image: lscr.io/linuxserver/duplicati:latest
      container_name: duplicati
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Bratislava
      volumes:
        - /mnt/duplicati/config:/config
        - /mnt/backups:/backups
        - /mnt:/source
      ports:
        - 8200:8200
      restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - /mnt/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - /mnt/sonarr/config:/config
      - /mnt/storage/series:/tv #optional
      - /mnt/prowlarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - /mnt/radarr/config:/config
      - /mnt/storage/movies:/movies #optional
      - /mnt/radarr/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - /mnt/bazarr/config:/config
      - /mnt/storage/movies:/movies #optional
      - /mnt/storage/series:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped